#give access to have super user level permissions
sudo: required

# Tell travis ci that we need docker preinstalled
services:
  - docker

# before install is going to be a series of commands before our tests are ran
before_install:
  - docker build -t sbenn9210/docker-react -f Dockerfile.dev ./frontend

# The script section contains all the different commands that need to be executed
# to run the test suite
script:
  - docker run sbenn9210/docker-react npm run test -- --coverage
